library("pcalg")
library("SMPracticals")
data(mathmarks)
suffStat <- list(C=cor(mathmarks), n=nrow(mathmarks))
pc.fit <- pc(suffStat, indepTest=gaussCItest, p=ncol(mathmarks), alpha=0.005)
plot(pc.fit,labels=colnames(mathmarks), main="Inferred DAG for mathmarks")